# Generated by Django 2.2.17 on 2020-12-17 13:32

from django.db import migrations, models
import djongo.models.fields
import managebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('body_text', models.TextField()),
                ('genre', djongo.models.fields.ArrayField(model_container=managebook.models.Genre)),
                ('authors', djongo.models.fields.ArrayField(model_container=managebook.models.Author)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('comments', djongo.models.fields.ArrayField(blank=True, model_container=managebook.models.Comment)),
            ],
        ),
    ]
